image:
  registry: wechaty/wechaty

network:
  - 8080:8080

build:
  command: npm install

run:
  command: npm start

envs:
  - name: WECHATY_LOG
    value: verbose
  
  - name: WECHATY_PUPPET
    value: wechaty-puppet-wechat
